### ISSUE TITLE
Implement CandidateSlot usecase: 4d

### ISSUE THREAD

**Issue by GrEFeRFeeD** [GrEFeRFeeD/intellistart-java-2022-oneweek#11]
1. Implement CandidateSlotService:
1.1. Validation CandidateSlot
1.2 Creation CandidateSlot
2. Implement CandidateController:
2.1. POST /candidates/current/slots
2.2. POST /candidates/current/slots/{slotId}

**Comment by guzeyarthur** [comment]
start work on 11.10.2022, expect to finish on 14.10.2022

**Comment by guzeyarthur** [comment]
What I did today?

1. reviewed the project;
2. reviewed and studied how to make REST requests on Spring;
3. wrote an implementation of CandidateController.createCandidateSlot to create one slot (POST) and started writing an implementation of CandidateSlotService.create. Created CandidateSlotDto class

What I plan to do?

1. complete the CandidateSlotService.create
2. write a validator for the CandidateSlot
3. write CandidateSlotService.create to add multiple CandidateSlots

What prevents me from doing what I need?

1. lack of knowledge about Spring

**Comment by guzeyarthur** [comment]
What I did today?

1. Figured out how to serialise the list of objects from JASON.
2. Figured out that you can't overload a method with the same mapping and PEST request and wrote out questions to ask the mentor to figure out how to add one or more slots for the same mapping.
3. Refined CandidateController.createCandidateSlot, CandidateSlotService.create methods but no validation yet 

What do I plan to do?

1. Write a validator for CandidateSlot
2. Implement editing a candidate slot and getting all candidate slots 
3. Throw all the necessary errors into the controller

What's stopping me from doing what I need to do?

Lack of knowledge about Spring

Translated with www.DeepL.com/Translator (free version)

**Comment by guzeyarthur** [comment]
What I did today?

1. Figured out how to serialize the list of objects from JASON.
2. Figured out that you can't overload a method with the same mapping and PEST request and wrote out questions to ask the mentor to figure out how to add one or more slots for the same mapping.
3. Refined CandidateController.createCandidateSlot, CandidateSlotService.create methods but no validation yet
What do I plan to do?

Write a validator for CandidateSlot
Implement editing a candidate slot and getting all candidate slots
Throw all the necessary errors into the controller
What's stopping me from doing what I need to do?

Lack of knowledge about Spring

**Comment by guzeyarthur** [comment]
What I did today?

1. Figured out how to serialize the list of objects from JASON.
2. Figured out that you can't overload a method with the same mapping and PEST request and wrote out questions to ask the mentor to figure out how to add one or more slots for the same mapping.
3. Refined CandidateController.createCandidateSlot, CandidateSlotService.create methods but no validation yet
4. Made my first request to the postmen

What do I plan to do?

1. Write a validator for CandidateSlot
2. Implement editing a candidate slot and getting all candidate slots
3. Throw all the necessary errors into the controller

What's stopping me from doing what I need to do?

1. lack of knowledge about Spring

**Comment by guzeyarthur** [comment]
13.10-20.10

**Comment by guzeyarthur** [comment]
13.10-20.10
What I did?

Add CandidateSlotDtoValidator.validateUpdateCandidateSlotDto, Edit CandidateSlotDtoValidator.validateCreateCandidateSlotDto; Edit CandidateController.updateCandidateSlot; Add CandidateController.getAllSlotsOfCandidate; Edit CandidateSlotService.update; Add CandidateSlotService.getAllSlotsOfCandidate; Add CandidateSlotRepository.getCandidateSlotsByUser and CandidateSlotRepository.getCandidateSlotsByUserAndDate; Add many exceptions for validate; Add documentations; Add some tests of Validate; 

What do I plan to do?

Edit the validator; Edit the conversion from DTO to object and from object to DTO (move the conversion logic to DTO); Finish the tests

What's stopping me from doing what I need to do?

lack of knowledge about Spring;

**Comment by guzeyarthur** [comment]
20.10-26.10
What I did?

Add tests for CabdidateSlotValidator.class and CandidateSlotService, Edit the CabdidateSlotValidator, Edit the conversion from DTO to object and from object to DTO, and Edit some bugs.

What do I plan to do?

Take a new task
Review code of other tasks of colleagues

What's stopping me from doing what I need to do?

lack of knowledge about Spring;
