### ISSUE TITLE
Implement InterviewerSlot usecase: 4d

### ISSUE THREAD

**Issue by GrEFeRFeeD** [GrEFeRFeeD/intellistart-java-2022-oneweek#12]
1. Implement InterviewerSlotService:
1.1. Validation InterviewerSlot
1.2. Creation InterviewerSlot
2. Implement InterviewerController: POST /interviewers/<interviewerId>/slots

**Comment by sashav389** [comment]
What I did yestarday?

reviewed the project;
reviewed and studied how to make REST requests on Spring and how to work with postman;
wrote an implementation of IterviewerController.createInterviewerSlot to create one slot (POST), created DTO for it and started validation of it

What I plan to do?

complete the IterviewerSlotService.create
make validator

What prevents me from doing what I need?
lack of knowledge about REST, Spring

**Comment by sashav389** [comment]
What I did yestarday?

Refactor a great part of code. 
Update validation logic.
Add new controller request fo updating slot.

What I plan to do?

Write tests for controllers and new methods.

What prevents me from doing what I need?
lack of knowledge in tests
