### ISSUE TITLE
Docker - containerize application (5h)

### ISSUE THREAD

**Issue by GrEFeRFeeD** [GrEFeRFeeD/intellistart-java-2022-oneweek#24]
- prepare method GET /hello, Response = "Interviewer Application"

**Comment by makskostyshen** [comment]
spend time: 3 h
what I did:
- containerize application with docker-compose
- add dockerignore
- push image to docker hub

what I plan to do:
- make a pull request
- make changes if necessary
- rebuild docker image according to pull request if necessary

what prevents me:
- now nothing
