### ISSUE TITLE
Refactor OverlappingService.isOvelapping() (3h)

### ISSUE THREAD

**Issue by GrEFeRFeeD** [GrEFeRFeeD/intellistart-java-2022-oneweek#26]
Two periods with same time should be logically overlapped.

Test case: isOvelapping(p1, p2) = true, if p1.from = p2.from and p1.to = p2.to.

**Comment by makskostyshen** [comment]
time spent: 2.5h

what I did:
- fix needed bug
- make little refactor
- finish the task

what I plan to do:
- solve merge conflict and make merge
- start working with another task

what prevents me:
- nothing
