### ISSUE TITLE
Implement creation and updating Booking use case (8h)

### ISSUE THREAD

**Issue by GrEFeRFeeD** [GrEFeRFeeD/intellistart-java-2022-oneweek#29]
Request:
POST /bookings (in case of creation)
POST /bookings/{bookingId} (in case of updating)
>{
	"interviewerSlotId": 1,
	"candidateSlotId": 2,
	"from": "12:30",
	"to": "12:30",
	"subject": "String",
	"description": "String"
}

Response:
>{
	"interviewerSlotId": 1,
	"candidateSlotId": 2,
	"from": "12:30",
	"to": "12:30",
	"subject": "String",
	"description": "String"
}

Throws:
>	interviewer_slot_not_found
	candidate_slot_not_found
	booking_not_found (in case of updating)
	slots_not_overlaping - in case if interviewerSlot and candidateSlot are not 
		overlapped in given period of time
	invalid_boundaries - in case when booking duration isn't 90 min
	invalid_subject - if validation of such field was failed
	invalid_descriptuon - if validation of such field was failed

**Comment by makskostyshen** [comment]
time spent: 1h
what I did:
- learn about controller structure practices
- create BookingDto

what I plan to do:
- start implementing create and update methods
- implement validation

what prevents me:
- nothing

**Comment by makskostyshen** [comment]
time spent: 2.5h
what I did:
- refactor Booking - change primary key to Long id
- create functionable methods updateBooking and createBooking without validation
- little refactor exceptions, CandidateService and InterviewerService: parts which are needed for my work

what I plan to do:
- start implementing validation

what prevents me:
- not sure about how to implement validation properly

**Comment by makskostyshen** [comment]
time spent: 2.5h
what I did:
- little refactor PerionService and TimeConverter
- implement dirty version of Dto validation
- learn about validation with java and spring

what I plan to do:
- visit Intellias' workshop about java validation to answer my questions
- start implementing validation properly

what prevents me:
- lack of knowledge of validation practices 
- I can't write code I'm not sure about

**Comment by makskostyshen** [comment]
time spent: 1.5 h
what I did:
- visit Intellias' workshop about java validation
- made decision to make a hard-code validation
what I plan to do:
- quickly code Controllers and Services
what prevents me:
- I can't comfortably write code I'm not sure about

**Comment by makskostyshen** [comment]
time spent: 3.5h
what I did:
- implement validation for creation and updating booking
- implement both controllers
- write documentation
- fix checkstyle
- little refactor exceptions

what I plan to do:
- start implementing tests for validation and BookingService

what prevents me:
- problems with electricity

**Comment by makskostyshen** [comment]
time spent: 1h
what I did:
- write test methods
- fix checkstyle
- try to fix occured problem with Mock

what I plan to do:
- fix Mock problem
- finish writing tests

what prevents me:
- problem with Mock test

**Comment by makskostyshen** [comment]
time spent: 3h
what I did:
- try to fix the bug by myself
- try to fix the bug with my teammate
- write other tests

what I plan to do:
- fix that bug
- write tests and maybe finish the task

what prevents me:
- lack of experience solving bugs with tests

**Comment by makskostyshen** [comment]
time spent: 3h
what I did:
- complete the functionality
- fix problems with MOCK tests
- create pull request

what I plan to do:
- solve merge conflict
- wait for approves or comments from my collegues about pull request
- make changes if needed
- attend the grooming and planning meeting,  discuss new tasks

what prevents me:
- nothing, I'm ready to work

**Comment by makskostyshen** [comment]
time spent: 3h
what I did:
- start solving merge conflict
- participate in grooming session

what I plan to do:
- finish solving merge conflict

what prevents me:
- a lot of code changes have been made in parallel

**Comment by makskostyshen** [comment]
time spent: 1,5 h
what I did:
- solve first merge conflict
- check my teammates pull request
- solve second merge conflict
- prepare postman collection for use cases
- close the task

what I plan to do:
- move forward

what prevents me:
- problems with electricity and connection that increased
