### ISSUE TITLE
Refactor Exception system (4h)

### ISSUE THREAD

**Issue by GrEFeRFeeD** [GrEFeRFeeD/intellistart-java-2022-oneweek#56]
Refactor already existing errors (throwing and processing).

All errors should be one-styled - instances of Exception.class.

Should be written in profile-based system (one Exception class with plenty of options to initialize). 

Profiles must contain next information:
- Error name (snake_style)
- Error Message
- HttpStatus
	
As a result, the Exception should have next methods:
- getName() 
- getMessage() [default]
-  getStatus()
	
All errors should be grouped into use cases:
- User:
   - InvalidInterviewerException
   - SelfRevokingException
   - UserAlreadyHasRoleException
   - UserHasAnotherRoleException
   - UserNotFoundException
   - NotInterviewerException
	
 - Slot:
   - CannotEditThisWeekException
   - InvalidBoundariesException
   - InvalidDayOfWeekException
   - CandidateSlotNotFoundException
   - InterviewerSlotNotFoundException
   - SlotIsOverlappingException
   - SlotIsBookedException
   - SlotNotFoundException
   - ExceededBookingLimitException

 - BookingLimit:
    - InvalidBookingLimitException

 - Booking:
   - BookingNotFoundException
   - InvalidDescriptionException
   - InvalidSubjectException
   - SlotsAreNotIntersectingException
	
Each group should have own ExceptionHandler class to handle exception based on their inner profile.

All handlers should pass ExceptionResponse object as a return type to the client.

**Comment by sonnka** [comment]
time spent: 2h
what we did:

- add user exception;
- add user exception handler;
- add booking limit exception;
- add booking limit exception handler;
- add slot exception;

what we plan to do:

- fix checkstyle errors;
- add slot exception handler;

what prevents us:

- nothing.
