### ISSUE TITLE
Implement WeekService: 2d

### ISSUE THREAD

**Issue by GrEFeRFeeD** [GrEFeRFeeD/intellistart-java-2022-oneweek#6]
1. Implement util method of parsing server localtime to number of week (start measurement from 01.01.2022).
2. Implement util method of parsing any date to number of week.
3. Implement GuestController:
2.1. GET /weeks/current
2.2. GET /weeks/next

**Comment by sonnka** [comment]
start work on 11.10.2022, expect to finish on 13.10.2022

**Comment by sonnka** [comment]
what I did?
          - reviewed the project architecture;
          - specified the issue;
          - implemented the method of parsing LocalDate into number of week;
          
what I plan to do?
          - implement the method of parsing LocalDate into day of week;
          - implement the method of parsing number of week and day of week into LocalDate;
          - implement GuestController;

what prevents me from doing what I need?
          - lack of knowledge about controllers;
          - lack of time.

**Comment by sonnka** [comment]
what I did?
- implemented the method of parsing LocalDate into day of week;
- implemented the method of parsing number of week and day of week into LocalDate;

what I plan to do?
- write tests for the implemented methods in WeekService;
- implement GuestController;

what prevents me from doing what I need?
- lack of knowledge about Spring and controllers;
- lack of knowledge about tests.

**Comment by sonnka** [comment]
what I did?

  - read some information about tests;
  - read some information about controllers;

what I plan to do?

  - write tests for the implemented methods in WeekService;
  - implement GuestController;

what prevents me from doing what I need?

  - lack of knowledge about Spring and controllers;
  - lack of knowledge about tests;
  - lack of time.

**Comment by sonnka** [comment]
what I did?

  - wrote tests for methods in WeekService;
  - implemented GuestController;
  - implemented the methods for GuestController in WeekService;

what I plan to do?

  - write tests for the new implemented methods in WeekService;
  - write tests for GuestController;

what prevents me from doing what I need?

  - lack of knowledge about tests.

**Comment by sonnka** [comment]
what I did?

- wrote tests for new methods in WeekService;
- wrote tests for GuestController;
- fixed some errors after pull request.

what I plan to do?

- merge my branch to main.

what prevents me from doing what I need?

- wait for approving.

**Comment by sonnka** [comment]
what I did today?

- refactored some methods in WeekService.

what I plan to do?

- take new task;

what prevents me from doing what I need?

- wait for merging.
