### ISSUE TITLE
Implement PeriodService: 4d

### ISSUE THREAD

**Issue by GrEFeRFeeD** [GrEFeRFeeD/intellistart-java-2022-oneweek#7]
1. boundaries validation
2. get from DB period by (from, to)
3. create new period
4. method getOrCreate(from, to) -> Period

**Comment by makskostyshen** [comment]
what I did today:
- reexplore project
- learn practices for implementing validators
- write simple period validators and time converter
- write tests

 what I plan to do:
- learn more about validators, discuss and chose one solution for all cases with the team
- implement a validation system

 what prevents me:
- lack of knowledge of validator practices
- not sure about Period creation mechanism in Project

**Comment by makskostyshen** [comment]
what I did today:
- learn practices for implementing validators
- discuss and chose general validator practice for project with team
- finish validation system
- write new and edit old tests

what I plan to do:
- start working on getting period from database when is needed
- implement overlapping check for period

what prevents me:
- lack of time

**Comment by makskostyshen** [comment]
what I did today:
- complete OverlapService
- write tests
- start learning Hibernate and getting objects from the database

what I plan to do:
- learn more about Hibernate
- made a decision on refactoring Period key or not
- complete getting period
- complete the task

what prevents me:
- lack of knowledge about Hibernate
- lack of time

**Comment by makskostyshen** [comment]
what I did today:
- learn more about Hibernate: queries, persistence, composite keys
- made a decision to not refactor Period Key
- wrote getPeriod method 
- complete the task and make a pull request

what I plan to do:
- choose the new task and start working

what I want:
- work with docker

what prevents me:
- nothing

**Comment by makskostyshen** [comment]
what I did today:
- fix style to correspond to checkstyle for my pull-request branch
- make refactoring for my pull-request branch suggested by teammates
- help teammate to sort out the problem with maven build for her pull-request branch
- create issue and outline future work with docker

what wasn't solved:
- problem with maven build for teammate's pull-request branch

what I plan to do:
- merge my branch to main
- start to learn docker

what prevents me:
- lack of knowledge about workflow and maven build
- my pull request isn't approved yet

**Comment by makskostyshen** [comment]
what I did today:
- write mock tests
- make code style and documentation changes
- discuss code style with teammates

what I plan to do:
- make other cosmetic changes
- wait for approvals of pull request

what prevents me:
- lack of my time
- lack of teammates' time

**Comment by makskostyshen** [comment]
what I did today:
- make code style and documentation changes
- refactor tests with parametrized
- face a problem with mock

what I plan to do:
- solve a problem with mock
- wait for teammates' approvals
- finish fixing my task

what prevents me:
- now nothing

**Comment by makskostyshen** [comment]
what I did today:
- fix tests, solve problem with mock
- refactor little: namings, documentation, tests

what I plan to do:
- get a review of my task, discuss comments about it, and maybe close it

what prevents me:
- lack of my and my teammates' time

**Comment by makskostyshen** [comment]
what I did today:
- fix mock tests to improve test coverage

what I plan to do:
- close the task

what prevents me:
- lack of my teammates' time
