### ISSUE TITLE
Implement BookingLimitService: 2d

### ISSUE THREAD

**Issue by GrEFeRFeeD** [GrEFeRFeeD/intellistart-java-2022-oneweek#8]
Implement mapping  in InterviewerController and getBookingLimitByInterviewer().

Request:
POST /interviwers/{interviewerId}/bookinglimit
{
	"bookingLimit": 123
}

Response:
{
        "userId": 10
	"weekNum": 20, 
	"bookingLimit": 123
}
Where weekNum is number of next week.

**Comment by GrEFeRFeeD** [comment]
> Hello, @GrEFeRFeeD I would like to contribute.

Hi, @DevPJ9! Unfortunately, I can't allow you to contribute to this as this is an educational project in courses provided by a commercial company :(

**Comment by sonnka** [comment]
time spent: 1h

what I did:

- began to implement method getBookingLimitByInterviewer() in BookingLimitService;

what I plan to do:

- implement all methods in BookingLimitService;
- begin to implement mapping in InterviewerController;

what prevents me:

- nothing.

**Comment by sonnka** [comment]
time spent: 1h

what I did:

- implemented mapping in InterviewerController;

what I plan to do:

- write tests for methods in InterviewerController and in BookingLimitService;

what prevents me:

- nothing.

**Comment by sonnka** [comment]
time spent: 0.5h

what I did:

- refactored method in BookingLimitService;

what I plan to do:

- write tests for methods in InterviewerController and in BookingLimitService;

what prevents me:

- nothing.

**Comment by sonnka** [comment]
time spent: 1h

what I did:

- added new requests in InterviewerController;
- refactored method in BookingLimitService;

what I plan to do:

- write tests for methods in InterviewerController and BookingLimitService;

what prevents me:

- nothing.

**Comment by sonnka** [comment]
time spent: 0.5h

what I did yesterday:

- wrote tests for methods of BookingLimitService;

what I plan to do:

- write tests for methods in InterviewerController;

what prevents me:

- nothing.

**Comment by sonnka** [comment]
time spent: 0.5h

what I did :

- refactored some methods in BookinfLimitService and InterviewerController;

what I plan to do:

- refactor some methods in BookinfLimitService and InterviewerController;

what prevents me:

- nothing.
